server:
  port: 8004
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: service-user_route
          uri: lb://service-user
          predicates:
              - Path=/api/service-user/**
          filters:
              - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: service-order_route
          uri: lb://service-order
          predicates:
            - Path=/api/service-order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: service-product_route
          uri: lb://service-product
          predicates:
            - Path=/api/service-product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: service-auth_route
          uri: lb://security-auth
          predicates:
            - Path=/api/security-auth/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

